
;* EC6809 CONSOLE I/O DRIVER

JSWIVE  EQU     $F000      ; SWI3 VECTOR LOCATION (SET INTO ROM LIKE IN FAG)
JIRQVE  EQU     $F000      ; IRQ VECTOR LOCATION  (SET INTO ROM LIKE IN FAG)

WTLDVI  EQU     $F033      ; GET // DATA INPUT
INIT    EQU     $F036      ; INIT OF VIA, ACIA, CRTC        
VIARDY  EQU     $F039      ; TEST // DATA READY        
JMPADR  EQU     $F03C      ; PUT CHAR ON SCREEN
GDTVIE  EQU     $F03F      ; GET // DATA INPUT WITH ECHO
ERTI    EQU     $F030      ; RETURN FROM INTERRUPT
ERTS    EQU     $F01B

COLDS   EQU     $CD00

        ORG     $D3E5

INCHN   FDB     JINCHN     ; INPUT CHARACTER WITHOUT ECHO
IHNDLR  FDB     ERTI       ; IRQ INTERRUPT HANDLER
SWIVEC  FDB     JSWIVE     ; SWI3 VECTOR LOCATION
IRQVEC  FDB     JIRQVE     ; IRQ VECTOR LOCATION
TMOFF   FDB     ERTS       ; TIMER OFF ROUTINE
TMON    FDB     ERTS       ; TIMER ON ROUTINE
TMINT   FDB     ERTS       ; TIMER INITIALIZATION
MONITR  FDB     JMONIT     ; MONITOR ENTRY ADDRESS
TINIT   FDB     ERTS       ; TERMINAL INITIALIZATION
STAT    FDB     JSTAT      ; CHECK TERMINAL STATUS
OUTCH   FDB     JMPADR     ; OUTPUT CHARACTER
INCH    FDB     JINCH      ; INPUT CHARACTER WITH ECHO

        ORG     $D370

;* INPUT CHARACTER WITHOUT ECHO
JINCHN  JSR     WTLDVI   
        ANDA    #$7F       ; CLEAR PARITY BIT
        PULS    PC

;* INPUT CHARACTER WITH ECHO
JINCH   JSR     GDTVIE
        ANDA    #$7F       ; CLEAR PARITY BIT
        PULS    PC

;* CHECK VIA STATUS (IF CHAR IS WAITING Z=1, ELSE Z=0)      
JSTAT   PSHS    A
        JSR     VIARDY
        PULS    A,PC 
        
;* MONITOR ENTRY ADDRESS
JMONIT  SWI             
        FCB     $08

;* CHANGE DEFAULT MEMEND VALUE (AS PER FAG)
        ORG     $CC2B
        FCB     $BE,$FF

		END		COLDS
